version: "3.9"

services:
  app:
    build: .
    container_name: ellis-app
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    restart: unless-stopped
    networks:
      - ellis-network
networks:
  ellis-network:
    driver: bridge